Moves spring controllers to ulisboa specifications
qub-it/fenixedu-legal-pt pull request #16
Opened 2024-05-10 13:36 UTC by joaofreitas-qubit

Relates with: #qubIT-Omnis-5831

2024-05-13 09:06 UTC, joaofreitas-qubit commented on src/main/java/org/fenixedu/ulisboa/integration/sas/servlet/SasInitializer.java
> -public class SasInitializer implements ServletContextListener {
stays

2024-05-13 09:06 UTC, joaofreitas-qubit commented on src/main/java/org/fenixedu/ulisboa/integration/sas/tasks/sicabe/IngestSasScholarshipSicabe.java
> -//Force task to be read only and process each report on its own transaction to avoid errors in a report affecting other reports
stays

2024-05-13 09:06 UTC, joaofreitas-qubit commented on src/main/java/org/fenixedu/ulisboa/integration/sas/service/sicabe/SicabeExternalService.java
> -import pt.dges.schemas.services.sicabe.v1.DadosAcademicosAlterarDadosAcademicosRestantesCasosSicabeErrorMessageFaultFaultMessage;
stays

2024-05-13 09:07 UTC, joaofreitas-qubit commented on src/main/java/org/fenixedu/ulisboa/integration/sas/util/SasPTUtil.java
> -public class SasPTUtil {
stays

2024-05-14 09:30 UTC, pabrantes requested changes

2024-05-14 09:30 UTC, pabrantes commented on pom.xml
>  					</execution>
@joaofreitas-qubit let's just checkout this file directly from master so it stops being seen as a change when it's only spacing.

2024-05-14 10:39 UTC, pabrantes approved these changes

2024-05-15 14:27 UTC, merged